### ISSUE TITLE
 Error: No rule to make target (verisim)

### ISSUE THREAD

**Issue by abdullahyildiz** [riscv-boom/riscv-boom#108]
I use commit 856f043999c7ee4fea05964a276f3b1f58553fa6.

When I type make in `verisim`, I get the following error:

`make: *** No rule to make target '/archive/HDD5/ayildiz/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig.v', needed by '/archive/HDD5/ayildiz/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig/VTestHarness.mk'.  Stop.`

It was working until today. I couldn't find the cause of this error.

**Comment by jerryz123** [comment]
Could you try running `make clean` and then `make` in `boom-template/verisim`?

**Comment by abdullahyildiz** [comment]
This is the output of `make clean` and then `make` commands in `boom-template/verisim`:

```
$ make clean
echo This target does not clean the generated-src directory
This target does not clean the generated-src directory
rm -rf ./simulator-*
$ make
make: *** No rule to make target '/archive/HDD5/ayildiz/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig.v', needed by '/archive/HDD5/ayildiz/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig/VTestHarness.mk'.  Stop.

```

**Comment by abdullahyildiz** [comment]
Sorry, I noticed that I use a custom verisim directory. This is the cause of the problem.
