### ISSUE TITLE
IRC/Slack channel?

### ISSUE THREAD

**Issue by pranith** [riscv-boom/riscv-boom#110]
Is there any interest in having an IRC or slack channel for BOOM? I think it will be really useful for some live discussion/questions.

**Comment by jerryz123** [comment]
There is a mailing list for BOOM-related questions. https://groups.google.com/forum/m/#!forum/riscv-boom

**Comment by seldridge** [comment]
The kids these days seem to be starting up Gitter channels left and right. This has the added benefit of an IRC interface that is still enabled! Chisel and FIRRTL both have one, e.g., https://gitter.im/freechipsproject/chisel3, in addition to mailing lists, SO tags, and GitHub issues (with these strongly moving towards feature requests/bug fixes only).

**Comment by pranith** [comment]
@jerryz123 I am aware of the mailing list, my question was about more real-time discussions :)

**Comment by pranith** [comment]
@seldridge @ccelio gitter.im sounds like a good fit. Is there interest in creating a channel for boom?

**Comment by pranith** [comment]
Since there is not much interest... closing this.
