### ISSUE TITLE
BOOM lacks breakpoint support

### ISSUE THREAD

**Issue by ccelio** [riscv-boom/riscv-boom#16]
BOOM currently lacks breakpoint support.  It would be nice to have it.

Things to note: 

1. The boom branch of rocket-chip disables the `breakpoint` test (so the necessary software to test this feature already exists):

https://github.com/ucb-bar/rocket-chip/blob/boom/src/main/scala/rocketchip/RocketTestSuite.scala#L153

2. The rocket core implements breakpoints and provides a lot of starting pointers for a BOOM implementation:

https://github.com/ucb-bar/rocket-chip/blob/master/src/main/scala/rocket/breakpoint.scala 
https://github.com/ucb-bar/rocket-chip/blob/master/src/main/scala/rocket/rocket.scala#L268

3. One of the challenges is handling a breakpoint on an instruction address in the presence of superscalar fetching.

**Comment by gobs-code** [comment]
wow,very nice.Thanks all~
