### ISSUE TITLE
Access exceptions caused by PTW are probably broken right now.

### ISSUE THREAD

**Issue by jerryz123** [riscv-boom/riscv-boom#170]
The D$ TLB handles both PTW and core requests, and does not differentiate between either. To re-enable PMPs, #123 ignores access exceptions thrown by the D$ TLB, since core requests check the PMPs in the LSU TLB instead.

However, PTW requests may still fail a PMP check, and that exception needs to propagate.

Essentially, the D$ needs to differentiate between core and PTW requests somehow.

**Comment by pentin-as** [comment]
Until you have done more closely L1D and LSU, I would like to try to make the following temporary correction:
 - TLB inside LSU only translate address;
 - D$ contains PMPChecker (instead LSU), which checks all requests (from LSU and PTW).

Additionally, I can say that PMP inside LSU contains one of the critical path that would be good to remove:
https://github.com/riscv-boom/riscv-boom/issues/224

What do you think about that?

**Comment by jerryz123** [comment]
The issue is this would require forking the TLB and PMPChecker from Rocket, which currently combines them in one module. I'm not sure how much work this would be, and in any case forking would leave behind a lot of duplicate code between BOOM and Rocket. 

It also looks like it will be challenging to split up the functionality of PMPChecker from the TLB, since on refills, the PMPChecker marks bits in the TLB entries.

**Comment by jerryz123** [comment]
Resolved in #275
