### ISSUE TITLE
Mismatch between short history and long history with no branch predictor?

### ISSUE THREAD

**Issue by donggyukim** [riscv-boom/riscv-boom#18]
I got an assertion fail when I ran rv64ui-p-simple even though I turned off the branch predictor:

```
 Assertion failed: [brpredictor] mistmatch between short history and very long history implementations.
     at brpredictor.scala:192 assert (r_ghistory_commit_copy === vlh_commit,
```

**Comment by ccelio** [comment]
What's the boom hash you're using? I may have made updates and I may not have bumped the boom branch of rocket-chip to match. 

Worst case, you can freely comment out that assert.

**Comment by ccelio** [comment]
I just pushed this, which hopefully won't give you a problem: https://github.com/ucb-bar/rocket-chip/commit/2fcf18cb0b8de39389a9598cfcda4280eff30a3f

**Comment by donggyukim** [comment]
I tried it with 4825d37ceef10a329ccaef84bb4247c6e8f34750 with serial port in testchipip. I couldn't try it with the latest commit with it due to coreplex type conflicts, but the failure doesn't appear with the latest commit in rocket-chip. Thus, I close it.

**Comment by ccelio** [comment]
Ah, you can use the latest boom commit with an older rocket-chip, you just need to apply `git revert` to it, to revert this commit (https://github.com/ucb-bar/riscv-boom/commit/3cdd4bd84891c7b5704f21ff2249ea2ba79a0f14) that updates boom to the latest lazyModule stuff.  You can check out my fpga repo on A5:/nscratch/celio/fpga-zynq/rocket-chip to see what versions I'm using together.

**Comment by donggyukim** [comment]
Your tip also works for me and I created a branch reverting that commit. Thanks, Chris!
