### ISSUE TITLE
Match number of physical registers to ROB size

### ISSUE THREAD

**Issue by jerryz123** [riscv-boom/riscv-boom#189]
Number of INT physical registers <= 32 + ROB_SIZE
Number of FP physical registers <= 32 + ROB_SIZE

**Comment by abejgonzalez** [comment]
If I am understanding this equation correctly, you are saying that the...

``# of Phys. Regs = # ISA Regs + ROB_SIZE``

However, this is worst-case scenario. Do we want to have the worst case as the "default" values?

**Comment by jerryz123** [comment]
Number of physical register should be <= isa regs + rob size.

In some configurations this is not the case, for those configurations we should decrease number of physical registers.

**Comment by jerryz123** [comment]
Resolved in #188
