### ISSUE TITLE
scall isn't being counted as a retired instruction

### ISSUE THREAD

**Issue by ccelio** [riscv-boom/riscv-boom#2]
Relatively benign, but the handling of scall uses a different execution path that doesn't trigger the "committed instruction" signal. 
- Pipeline is held up (serialized) for SCALL instruction.
- SCALL is sent to CSRFile, which redirects the PC (like an exception).

**Comment by aswaterman** [comment]
I don't think this is a bug.  SCALL should never retire.

**Comment by ccelio** [comment]
Ah, thanks for the input. I see, reading the Privileged Spec, that it says:

> Executing an ECALL instruction causes an Environment Call exception.

The SCALL description in the user manual was less clear.  I suggest both manuals should be more explicit that the instruction's side-effect does not include incrementing the instret counter.
