### ISSUE TITLE
Documentation on load/store unit mentions non-existing variables

### ISSUE THREAD

**Issue by jeehoonkang** [riscv-boom/riscv-boom#251]
Documentation on load/store unit mentions non-existing variables.  The article I'm referring to is: https://github.com/riscv-boom/riscv-boom/blob/master/docs/sections/load-store-unit.rst (https://docs.boom-core.org/en/latest/sections/load-store-unit.html#id1)

For example, it seems `laq_st_mask` and `laq_entry_val` mentioned in the article seem renamed to `laq_st_dep_mask` and `laq_addr_val`, I guess.  It seems `laq_val` is removed, but I am not sure of.

**Comment by abejgonzalez** [comment]
Hey!

Thanks for pointing this out. The BOOM documentation was initially ported from Chris's initial BOOM documentation PDF so a couple places in it are out of date. We are planning on fixing this soon! If you have questions after looking at the LSU code feel free to reach out and we can try to help out!
