### ISSUE TITLE
Installing project riscv-isa-sim error

### ISSUE THREAD

**Issue by nicolast0604** [riscv-boom/riscv-boom#351]
Installing project riscv-isa-sim

Removing existing riscv-pk/build directory
Configuring project riscv-pk
Building project riscv-pk
gcc: error: unrecognized argument in option ‘-mcmodel=medany’
gcc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
make: *** [file.o] Error 1

**Comment by jerryz123** [comment]
What version of `riscv-tools` are you building? This error is typically due to not finding `riscv64-unknown-elf-gcc` on your `PATH`.
