### ISSUE TITLE
what is <TRACE_FILE>, filename in boom-template ?

### ISSUE THREAD

**Issue by nicolast0604** [riscv-boom/riscv-boom#352]
You should find the traces (*.out) in emulator/output/. To generate the visualization run:

   $ boom/util/pipeview-helper.py -f <TRACE_FILE> > cleaned_trace.out
   $ path_to_gem5/util/o3-pipeview.py --color --store_completions -o pipeview.out cleaned_trace.out
You can view the visualization by running:

   $ less -r pipeview.out

**Comment by jerryz123** [comment]
TRACE_FILE should be the `.out` files in `boom-template/emulator/output`.
If `O3PIPEVIEW_PRINTF` is enabled and your simulator is being called correctly, there should be a non-empty `.out` file there.
