### ISSUE TITLE
Linux Kernel Panic for 80 INT Registers

### ISSUE THREAD

**Issue by gkaplayan** [riscv-boom/riscv-boom#403]
**Type of issue**: bug report

**Impact**:  new rtl

**Development Phase**: request 

**Other information**
I got an error message when booting linux. It passes all RISC-V tests.
Configuration: The number of INT Registers: 80 
Error message: 
sstatus: 0000000200000100 sbadaddr: fffffffb63b62868 scause: 000000000000000d
Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b

Other trials: 128 INT Reg, 70 INT Reg => Works fine for Linux

**Comment by jerryz123** [comment]
Sorry for delayed response, can you give me exact steps to replicate this? 
Specifically, are you building this with Chipyard? How are you booting this. In SW Sim? Or FPGA? What command did you use to build the simulator and run the simulation?
