### ISSUE TITLE
No repair mechanism for return address stack (RAS)

### ISSUE THREAD

**Issue by hyf6661669** [riscv-boom/riscv-boom#428]
Hi, I find that there is no repair mechanism for RAS in riscv-boom, there are many reasons that will cause a pipeline flush:
1. jalr/conditional branch mispredictions
2. misspeculation load instructions
3. instructions which are related to the core/ISA architecture, like fence/fence.i/sfence/csr

The instructions (or fetch packets) behind these instructions may change the contents of RAS before the pipeline flush happens. But after the pipeline is flushed, the latter "refetched" instructions will see the modified RAS, instead of the original RAS. Under this situation, the following CALL/RET instructions are very likely to be mispredicted. However, use checkpoints for the whole RAS could be very expensive. Is there any cost-effective methods for repairing RAS?

**Comment by ccelio** [comment]
This is a very good observation.

Unfortunately, at this time, it is left as an exercise to the reader to provide pull requests that improve the situation. =) I've not searched the published literature myself, but perhaps "return address stack repair" might bring up some hints for you to investigate.

**Comment by jerryz123** [comment]
This will be addressed in a upcoming version of BOOM. I have a version of the RAS that repairs the stack index and the top-of-stack address. See this old micro paper for details: https://mrmgroup.cs.princeton.edu/papers/micro31_retstack.pdf.

By only snapshotting the index and top-of-stack address, the snapshots can be stored efficiently in 1R1W SRAMs (1R for repairs, 1W for fetch). The repair procedure is also simple, whenever a branch is mispredicted, the index and entry at the top of the RAS are restored to whatever they were when that branch was initially fetched.
