### ISSUE TITLE
Fix Pipeview 

### ISSUE THREAD

**Issue by jfustos** [riscv-boom/riscv-boom#429]
**Type of issue**: bug report

**Impact**: new rtl

**Development Phase**: request

**Other information**

Pipeview is currently broken in boom, at least in commit:
commit 2a0ea2e7acfd4605eed513e15062848e4e5be309

When the trace is generated, all of the fetches have a zero for a sequence number, which produces a pipeview that only shows the fetches. This was happening because the sequence number is trying to be read from the f3_fetch_bundle, but the sequence number is not being assigned until the Fetch Buffer.

I fixed this by instead assigning the sequence number to the f3_fetch_bundle, at least it looks fixed to me when I try to generate the pipeview. Someone more experienced with BOOM may want to look at it though. The change is as follows:

```
diff --git a/src/main/scala/ifu/fetch-control-unit.scala b/src/main/scala/ifu/fetch-control-unit.scala
index 2c41f914..05215353 100644
--- a/src/main/scala/ifu/fetch-control-unit.scala
+++ b/src/main/scala/ifu/fetch-control-unit.scala
@@ -501,6 +501,15 @@ class FetchControlUnit(implicit p: Parameters) extends BoomModule
   //-------------------------------------------------------------
 
   when (f3_fire) {
+    for (i <- 0 until fetchWidth) {
+      if (i == 0) {
+        f3_fetch_bundle.debug_events(i).fetch_seq := fseq_reg
+      } else {
+        f3_fetch_bundle.debug_events(i).fetch_seq := fseq_reg +
+          PopCount(f3_fetch_bundle.mask.asUInt()(i-1,0))
+      }
+    }
+    
     r_f4_req := f3_req
     r_f4_fetchpc := f3_imemresp.pc
     r_f4_taken := f3_taken
@@ -526,14 +535,6 @@ class FetchControlUnit(implicit p: Parameters) extends BoomModule
   fb.io.status := io.status
   fb.io.bp     := io.bp
 
-  for (i <- 0 until fetchWidth) {
-    if (i == 0) {
-      fb.io.enq.bits.debug_events(i).fetch_seq := fseq_reg
-    } else {
-      fb.io.enq.bits.debug_events(i).fetch_seq := fseq_reg +
-        PopCount(f3_fetch_bundle.mask.asUInt()(i-1,0))
-    }
-  }
 
   //-------------------------------------------------------------
   // **** FetchTargetQueue ****
```

**Comment by jerryz123** [comment]
Great catch, this likely broke when we added another pipeline stage to the instruction-fetch-unit.
Can your PR this? Your code looks good to me.
