### ISSUE TITLE
0x7ffff9a0 + 0x724 = 0xffffffffffe000c4 instead 0x800000c4

### ISSUE THREAD

**Issue by pentin-as** [riscv-boom/riscv-boom#44]
boom-template 489f49ff2380806a8aa186416cbdb046adfee619
boom: template 1eb08e0d4c98607997874639ba9b94c44f010884
rocket-chip: master 7e75d63ba6b4c1b50aaaf920e1c693ef6acf51d7

    800029a0:	ffffd797          	auipc	a5,0xffffd
    800029a4:	72478793        addi	a5,a5,1828 # 800000c4 <trap_entry>

**Comment by pentin-as** [comment]
alu in csr_exe_unit keeps the signal valid two cycles. As a result, regfile has two entries and the a5 register references an invalid entry.

![1](https://user-images.githubusercontent.com/30556064/32825385-d20402a8-c9b2-11e7-8cbf-1b6dff316055.png)

**Comment by ccelio** [comment]
Can you break this down into a small, reproducible test case? 

Can you show the iregfile writeports in the waveform that show the write enable and write address?

**Comment by ccelio** [comment]
Sorry, I'm confused by what the issue is. Is the problem that an addition of two numbers computes the wrong answer, or is the problem the ALU asserts valid for two cycles when it should only assert valid for one cycle?

**Comment by pentin-as** [comment]
regfile
![regfile](https://user-images.githubusercontent.com/30556064/32830349-ae059524-ca16-11e7-82a3-5f83f3425367.png)

information is set in two registers: 6 and 14

**Comment by pentin-as** [comment]
The waveform resp_valid is equal to the waveform of the req_valid signal.

![resp after req](https://user-images.githubusercontent.com/30556064/32830720-f454af00-ca17-11e7-9841-e9492d5181c2.png)

I will continue to analyze.

**Comment by pentin-as** [comment]
Sorry. I think I was wrong. Temporarily close the issue.

**Comment by pentin-as** [comment]
Sorry. I think I was wrong. Temporarily close the issue.

**Comment by pentin-as** [comment]
Yes, I was wrong. Sorry.
