### ISSUE TITLE
Will the SonicBOOM be opensource?

### ISSUE THREAD

**Issue by hyf6661669** [riscv-boom/riscv-boom#465]
I find that your team successfully develop SonicBOOM (boom-v3):
https://carrv.github.io/2020/papers/CARRV2020_paper_15_Zhao.pdf
Do you plan to make it opensource? If yes then what time?

**Comment by jerryz123** [comment]
We plan on tagging the release this Sunday, to coordinate with a release of Chipyard 1.3. 

Users interested in using SonicBOOM will be able to checkout Chipyard 1.3 to generate SonicBOOM RTL and run simulations.

**Comment by hyf6661669** [comment]
@jerryz123 Much thanks..
