### ISSUE TITLE
How to enable RSB in the latest boom

### ISSUE THREAD

**Issue by hz1490919302** [riscv-boom/riscv-boom#478]
In boom, RAS does not seem to work by default.

**Comment by jerryz123** [comment]
What do you mean,? RAS works in default configuration

**Comment by hz1490919302** [comment]
Comments I saw elsewhere：
https://github.com/riscv-boom/boom-attacks/issues/3#issuecomment-561804329

**Comment by jerryz123** [comment]
That issue has since been resolved.

**Comment by hz1490919302** [comment]
I was able to successfully run the conditional branch mispredict and the indirect branch mispredict attacks with this chipyard  and the SmallBoomConfig. However the return stack buffer attack did not recover the correct secret. Therefore, before you reply, I suspect that RAS is not working.

**Comment by jerryz123** [comment]
I am certain the RAS works. The problem is that we did not finish the implementation of the RAS attack in that repo
