### ISSUE TITLE
Question about bim.scala in SonicBoom

### ISSUE THREAD

**Issue by hyf6661669** [riscv-boom/riscv-boom#485]
Here:
https://github.com/riscv-boom/riscv-boom/blob/master/src/main/scala/ifu/bpd/bim.scala#L89-L104

```
    when (s1_update.bits.br_mask(w) ||
      (s1_update.bits.cfi_idx.valid && s1_update.bits.cfi_idx.bits === w.U)) {
      val was_taken = (
        s1_update.bits.cfi_idx.valid &&
        (s1_update.bits.cfi_idx.bits === w.U) &&
        (
          (s1_update.bits.cfi_is_br && s1_update.bits.br_mask(w) && s1_update.bits.cfi_taken) ||
          s1_update.bits.cfi_is_jal
        )
      )
      val old_bim_value = Mux(wrbypass_hit, wrbypass(wrbypass_hit_idx)(w), s1_update_meta.bims(w))

      s1_update_wmask(w)     := true.B

      s1_update_wdata(w)     := bimWrite(old_bim_value, was_taken)
    }
```

When the bim is updated, JAL/JALR instruction will also change the 2-bit counter value in a bim-entry. Because we will have 
```
(s1_update.bits.cfi_idx.valid && s1_update.bits.cfi_idx.bits === w.U) = 1
```
But I think bim should only be used to predict conditional branch instruction. Could you please tell me your thought here?

**Comment by jerryz123** [comment]
You are right, it should check the br_mask as well to filter out unconditional jumps

**Comment by hyf6661669** [comment]
@jerryz123 
Thanks for your reply. By the way, could you please share the papers that you use as reference for the loop predictor in BOOM ?

**Comment by jerryz123** [comment]
It is a simplified approximation of the predictor described in https://www.jilp.org/vol9/v9paper6.pdf
