### ISSUE TITLE
Question about indirect branch prediction

### ISSUE THREAD

**Issue by Lingrui98** [riscv-boom/riscv-boom#489]
**Type of issue**: question
I found that BOOM does not have an indirect branch predictor for non-return unconditional jump target prediction. Currently the indirect jump targets are preserved in uBTB and BTB. Is there a plan to implement such a component? Or are there any reasons not having it?

**Comment by jerryz123** [comment]
Direct branches and returns are far more frequent, so I focused on improving performance of those branches first.
I think an indirect predictor would be a great contribution, especially one that could be composed on top of the existing predictors,
