### ISSUE TITLE
hello,I am newer,but I am interested in this project. how can I join in it 

### ISSUE THREAD

**Issue by changeyourname** [riscv-boom/riscv-boom#5]

**Comment by ccelio** [comment]
For questions/discussions:
https://groups.google.com/forum/#!forum/riscv-boom

For documentation on how BOOM works:
http://ccelio.github.io/riscv-boom-doc/

A short TODO list:
https://github.com/ucb-bar/riscv-boom/blob/master/TODO.md

I'll leave it up to you to decide what you're interested in. Just start playing with it, running programs, reading the code, and deciding what you think needs improvement.
