### ISSUE TITLE
fcsr 'invalid operation' flag is not set

### ISSUE THREAD

**Issue by JaewonHur** [riscv-boom/riscv-boom#503]
**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: proposal

**Other information**

Hi, there is a mismatch between spike (rocket) and boom when doing `fdiv` operation.
In the test case below, spike and rocket set `Invalid Operation` flag in `fcsr`, 
but boom does not set.

Here is test case.
The buggy assembly file is `test_p.S` and you can make binary (`test_p.riscv`) after running `make` 
Boom v2, v3 all affected.

[test.zip](https://github.com/riscv-boom/riscv-boom/files/5590334/test.zip)

**Comment by jerryz123** [comment]
Thanks, there were some bugs with the implementation of BOOM's FDivSqrt unit. You can check out the fixes in the `mem2` branch.

**Comment by JaewonHur** [comment]
Thanks,

close the issue.

**Comment by zhangkanqi** [comment]
But this bug seems to be still unfixed.
