### ISSUE TITLE
the computer configuration to run riscv-boom on the PC

### ISSUE THREAD

**Issue by liaolin1997** [riscv-boom/riscv-boom#509]
Hello，Could you please tell me about know the limited comfiguration of  the PC to support run risc-v boom model?For example，the size of the running memory or the core numbers of the CPU...

**Comment by jerryz123** [comment]
Minimum requirements are single-core machine with at least 16 GB of RAM.
Recommended is quad-core with at least 32GB of RAM, especially if you target a larger config
