### ISSUE TITLE
How to specify which functional unit in a execution unit?

### ISSUE THREAD

**Issue by ghost** [riscv-boom/riscv-boom#523]
How to specify which functional unit in a execution unit?

**Comment by lxu28973** [comment]
Maybe you can see the code in execution-units.scala.
For example, here is the code around line 140:
```
    for (w <- 0 until int_width) {
      def is_nth(n: Int): Boolean = w == ((n) % int_width)
      val alu_exe_unit = Module(new ALUExeUnit(
        hasJmpUnit     = is_nth(0),
        hasCSR         = is_nth(1),
        hasRocc        = is_nth(1) && usingRoCC,
        hasMul         = is_nth(2),
        hasDiv         = is_nth(3),
        hasIfpu        = is_nth(4) && usingFPU))
      exe_units += alu_exe_unit
    }
```
You can see that every alu_exe_unit's functional units depend on the int_width which I think is the number of int execution units.
For  instance, if you only have one alu_exe_unit, the unit will contains all the functional units shown above (JmpUnit, CSR, Rocc(if you use it), Mul, Div, Ifpu(if you use it)).

If you want to specify which functional unit in a execution unit, maybe you need to modify the code.
