### ISSUE TITLE
Configuration of boom tool chain

### ISSUE THREAD

**Issue by hqw-lantian** [riscv-boom/riscv-boom#526]
I have tried ①--with-arch=rv64gc --with-abi=lp64d --with-cmodel=medany --enable-multilib② --with-arch=rv64g --with-abi=lp64 --with-cmodel =medany --enable-multilib, but boom does not work

**Comment by jerryz123** [comment]
What do you mean boom does not work? Did it fail to execute your test binary? How are you compiling and running your binary. Did your binary work with spike?
