### ISSUE TITLE
How to change the code of bootrom?

### ISSUE THREAD

**Issue by Sjf-bianhuakuai** [riscv-boom/riscv-boom#530]
Hi,
     I'd like to change the code of bootrom in the Boom then I change the bootrom.S in generators/rocket-chip/bootrom . But the code in bootrom of simulator is not same as the bootrom.S which I modified . It keep it as it is. What should I do?
     Is it necessary to modify the bootrom.S when  the muti-core-boom-simutor can run multi-thread code?

**Comment by jerryz123** [comment]
Are you building boom out of chipyard? The bootrom is in generators/testchipip.

It should not be necessary to modify the bootrom to run multithreaded code. All harts execute the bootrom, then jump into the loaded binary. The harts can read mhartid to determine their hartids.
