### ISSUE TITLE
Question about future releases

### ISSUE THREAD

**Issue by Lingrui98** [riscv-boom/riscv-boom#532]
**Type of issue**: question

Will future versions of BOOM decouple branch prediction from instruction fetch?

**Comment by jerryz123** [comment]
Decoupled in what sense? As in allow it to run ahead and independently of instruction fetch? 
This is something that should be done, but I don't think I will have time to work on this.

**Comment by Lingrui98** [comment]
Yes, that's exactly what I meant. Thanks :)

> Decoupled in what sense? As in allow it to run ahead and independently of instruction fetch?
> This is something that should be done, but I don't think I will have time to work on this.
