### ISSUE TITLE
Do you have a plan for DCache LRU replacement?

### ISSUE THREAD

**Issue by JaewonHur** [riscv-boom/riscv-boom#548]
Hi,
I'm watching on the Boom DCache implementation, and I found that it uses only random replacement policy.
Is there any implementation of PLRU replacement policy for DCache? 
or do you have a plan for it?

**Comment by jerryz123** [comment]
There is no implementation, but this should not be too difficult to add. I don't have plans to add this for now.

**Comment by JaewonHur** [comment]
Thanks for quick response.
