### ISSUE TITLE
Why don't use BIM,BTB,TAGE,LOOP for NLP?

### ISSUE THREAD

**Issue by ddxoxpp** [riscv-boom/riscv-boom#556]
I notice that predictors (BIM, BTB, TAGE, LOOP) can make predictions in S1, so why don't use them in NLP for  preciser NLP prediction?

**Comment by jerryz123** [comment]
Why do you think they can make predictions in S1?

**Comment by ddxoxpp** [comment]
They get next pc in S0, and read syncReadMem, and get read result in S1, and make predictions in S1. Is the timing too tight to do this?

**Comment by jerryz123** [comment]
Timing is too tight.
