### ISSUE TITLE
BOOM in master-3.1 branch cannot boot Linux

### ISSUE THREAD

**Issue by eugene-tarassov** [riscv-boom/riscv-boom#561]
**Type of issue**: bug report

2-way 1-core BOOM from master-3.1 hangs during Linux boot when the kernel tries to start first user space process.
I cannot tell exact location of the hang - JTAG debugger cannot halt the processor - timeout.

It works OK if I set the Chicken Bit.
BOOM from the master branch works OK.
RocketChip cores work fine.

I'm using this repo [https://github.com/eugene-tarassov/vivado-risc-v](https://github.com/eugene-tarassov/vivado-risc-v) to to build FPGA RISC-V SoC and boot Debian Linux.

Is it a known problem?

**Comment by jerryz123** [comment]
That's is an experimental branch currently
