### ISSUE TITLE
What is the format of the value in the floating-point register?

### ISSUE THREAD

**Issue by Yujie-Cui** [riscv-boom/riscv-boom#562]
I am studying the execution process of floating point instructions in Boomv3. I started with a simple `fadd.s` instruction. 
I added the code to output the value of the register in FPUUnit class in boom/src/main/scala/exu/execution-units/functional-unit.scala. But the output result does not completely correspond to the IEEE754 of floating-point numbers.

The code I added is:

```
when(io.req.bits.uop.uopc === uopFADD_S  ){
printf("------------------FPUUnit------------------------------\n")
printf("rs1 :%x, rs2 :%x \n",io.req.bits.rs1_data, io.req.bits.rs2_data)
printf("io.req.bits.uop %d\n", io.req.bits.uop.uopc)
printf("io.resp.bits.uop %d\n", io.req.bits.uop.uopc)
printf("io.resp.bits.data %x\n", io.resp.bits.data )
printf("\n\n")
}
```

Look at the following two instructions, the value of f5 in instruction 005470d3 is 0, and the value of f8 is 1.5.

 ```
  10314:	d01072d3          	fcvt.s.wu	f5,x0
   10318:	005470d3          	fadd.s	f1,f8,f5
```

And the output of Boom is: 
```
------------------FPUUnit------------------------- -----
rs1 :1f01fffff00400000, rs2 :1ffefffff00000000
io.req.bits.uop.inst 005470d3
io.req.bits.uop 87
io.resp.bits.uop 87
io.resp.bits.data 1ffefffff00000000
```

Why don't the values in rs1 and rs2 completely correspond to 0 and 1.5?

thanks!

**Comment by jerryz123** [comment]
They are stored in the internal recoded format operated on by Berkeley Hardfloat.
https://github.com/ucb-bar/berkeley-hardfloat
