### ISSUE TITLE
Incorrect jump address on specific condition.

### ISSUE THREAD

**Issue by JaewonHur** [riscv-boom/riscv-boom#569]
**Type of issue**: bug report 

**Impact**: rtl refactoring

**What is the current behavior?**
When the `io_cpu_redirect` signals from both memory disambiguation and branch prediction are asserted at the same cycle,
It seems BOOM select wrong pc.

**Please tell us about your environment:**
I'm using BOOM which is customized from tag v1.3.
But I only added a logic in ROB and instrumentation for monitoring, which should not affect the behavior of BOOM.
I was not able to reproduce the bug with the original BOOM, 
but I think it is because the case is so specific to easily reproduce.

I give you the object dump and vcd file.
The case is like follow:
1. `0x8060003c: 0x003b3027   fsd   ft3, 0(s6)` is dispatched.
2. `0x80600050: 0x00094a03   lbu s4, 0(s2)` is dispatched.
3. The load address is calculated earlier and it bypass the store (They actually have same address).
4. `0x8060007c: 0x0dbbf463    bgeu s7, s11, 80600144` is fetched and next pc is mispredicted.
5. Store address is finally calculated and BOOM knows that load value is incorrect.
    At the same time branch misprediction is also resolved.
6. `io_cpu_redirect` signals are asserted from both sources at the same cycle.
7. In this case, the pc should jump to `0x80600050` but the pc jumps to incorrect `0x80600058`

You can find the suspicious `io_cpu_redirect` at 151393 ps.

[bug.zip](https://github.com/riscv-boom/riscv-boom/files/7351359/bug.zip)

**Comment by jerryz123** [comment]
Thanks. I'll take a look tomorrow. Can you post what commit your book is modified from? Not sure what tag 1.3 is.

**Comment by jerryz123** [comment]
I don't understand something here. The waveform has `flush_commit_mask` high, but `io.commit.uops(0).flush_on_commit` low, which seems to contradict the RTL. Perhaps I'm not reading the same RTL you are simulating, though.

![image](https://user-images.githubusercontent.com/14086183/137456201-1ec88587-46d0-4414-a8cd-b8f4fadee32e.png)

**Comment by JaewonHur** [comment]
It seems I mis-interpreted the vcd file.
For experiment I added some logic in RoB which interpret `slli zero, zero, 0` to flush RoB on commit.

There seems no memory ordering fault occurred, 
but the branch misprediction and my custom logic conflicts and made the CPU do wrong thing.

Thanks for guiding.

**Comment by JaewonHur** [comment]
It is not the bug in BOOM.
