### ISSUE TITLE
Instruction address misaligned exception not triggered on jump to misaligned address 

### ISSUE THREAD

**Issue by sammy17** [riscv-boom/riscv-boom#574]
**Type of issue**: bug report 

**Impact**: unknown

**Development Phase**: request

**Other information**

I have the following instruction sequence where the jalr instruction jumps to a misaligned address. Ideally, jalr instruction should cause an **instruction address misalignned exception**, but BOOM jump to the misaligned address and execute the instruction at that address without triggering any exception. 
```
00000000800050a0 <main>:
    800050a0:	00000317          	auipc	t1,0x0
    800050a4:	01c30313          	addi	t1,t1,28 # 800050bc <sub_1>
    800050a8:	c0e30313          	addi	t1,t1,-1010

00000000800050ac <main_j1>:
    800050ac:	3f5300e7          	jalr	1013(t1)

00000000800050b0 <main_return>:
    800050b0:	ffffda17          	auipc	s4,0xffffd
    800050b4:	7c4a0a13          	addi	s4,s4,1988 # 80002874 <test_done>

00000000800050b8 <main_end>:
    800050b8:	000a0067          	jr	s4

00000000800050bc <sub_1>:
    800050bc:	039b76b3          	remu	a3,s6,s9
    800050c0:	22230fd3          	fsgnj.d	ft11,ft6,ft2
    800050c4:	00da0533          	add	a0,s4,a3
    800050c8:	0000100f          	fence.i
```
In other words, BOOM jumps to 0x800050be and executes 0x0fd3039b (read instr mem half from 800050bc and a half from 800050c0) as an instruction.
Spike and rocket-chip simulations behave as expected.

Attached test binary, spike log, BOOM rtl trace log and assembly file.   

**What is the current behavior?**
No exception triggered when jumping to a misaligned address

**What is the expected behavior?**
Instruction misaligned address should trigger when jumping to a misaligned address.

**Please tell us about your environment:**
    - version: e252e797c21aa3bf860cb9d67c6009ef00c5916f
    - os: `Linux 3.10.0-1160.36.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux`
    - build environment: https://github.com/ucb-bar/chipyard/commit/b5d013190d637e634113cb5179f8c8885df1945a

**What is the use case for changing the behavior?**
Correct exception behavior as mentioned in the privilege spec

**Trace logs and test:**
[boom_2.log](https://github.com/riscv-boom/riscv-boom/files/7406683/boom_2.log)
[spike_2.log](https://github.com/riscv-boom/riscv-boom/files/7406684/spike_2.log)
[test_2.zip](https://github.com/riscv-boom/riscv-boom/files/7406685/test_2.zip)

**Comment by jerryz123** [comment]
From section 2.5 of the unprivileged ISA:
> Instruction-address-misaligned exceptions are not possible on machines that support extensions
with 16-bit aligned instructions, such as the compressed instruction-set extension, C.

C-extension is always enabled in BOOM, so instruction misaligned is not possible.
