### ISSUE TITLE
what is the parameter "memWidth" mean in BOOM? 

### ISSUE THREAD

**Issue by Hsiang0816** [riscv-boom/riscv-boom#575]
In the code of "lsu.scala", I have observed that "memWidth" is used a lot, but I am not sure what it means? 

I hope someone can help me out. 

Thank you very much!

**Comment by jerryz123** [comment]
It represents how many loads can be issued per cycle. 1/2 are the supported values.

**Comment by Hsiang0816** [comment]
Hi, I still have some question.

Does "loads" mean "load instruction"? And does the action of issue mean issuing memory access from LSU to cache/memory?

Thank you!

**Comment by jerryz123** [comment]
Yes, and yes.

**Comment by Hsiang0816** [comment]
Thank you!!
