### ISSUE TITLE
Question: what's the different between arch_valids and valids in ROB CommitSignals?

### ISSUE THREAD

**Issue by w1nda** [riscv-boom/riscv-boom#595]
https://github.com/riscv-boom/riscv-boom/blob/ad64c5419151e5e886daee7084d8399713b46b4b/src/main/scala/exu/rob.scala#L118-L121

**Comment by jerryz123** [comment]
arch_valids is set for instructions that are seen to architecturally commit.
valids is set for instructions that drain from the ROB at the commit head.
Some instructions will be valid, but not arch_valid.
The use case is for the shadowed instructions in a short-forwards-branch. See the SonicBOOM CARRV paper for more details.
