### ISSUE TITLE
Question about PipelinedMultiplier

### ISSUE THREAD

**Issue by zhaohaosen-cpu** [riscv-boom/riscv-boom#598]
In RocketChip, PipelinedMultiplier is a parameterizable unit. In the first clock cycle, it stores operands and in the second clock cycle, it computes the result. The multiplication operation is finished in two clock cycles. So I am wondering why in BOOM, the default imulLatency is 3 but not 2?

**Comment by jerryz123** [comment]
The default settings are pretty conservative. From a glance, it looks like you should be able to set it to 2.
