### ISSUE TITLE
Failing ma_fetch test

### ISSUE THREAD

**Issue by ccelio** [riscv-boom/riscv-boom#62]
The `template` branch (used by https://github.com/ccelio/boom-template/commit/98312e162be9673116ed2b0db9191f149006528a) now fails the `ma_fetch` test in riscv-tests (the newer tests explore more cases).

**Comment by jerryz123** [comment]
Temporarily fixed in https://github.com/riscv-boom/riscv-boom/commit/b422205a68f9357458b7b02562d497d9f3d87918. Still needs a real fix

**Comment by jerryz123** [comment]
Fixed (sort of) in #231
