### ISSUE TITLE
ECC support for BOOM I Cache and Cache

### ISSUE THREAD

**Issue by Kevin99214** [riscv-boom/riscv-boom#660]
**Type of issue**: feature request 

**Impact**: new rtl / unknown

**Development Phase**: request 

**What is the use case for changing the behavior?**
In reference to this [issue](https://github.com/riscv-boom/riscv-boom/issues/579) and the [riscv-platform-spec](https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.adoc), currently rocket's ICache and DCache supports SECDED-ECC whereas BOOM's ICache and DCache does not. 
Is there any chance ECC will be added to BOOM ICache and DCache?

**Comment by Kevin99214** [comment]
Closing this as it seems NBDCache does not support ECC. (#363 and chipsalliance/rocket-chip#495)

**Comment by jerryz123** [comment]
BOOM does not use NBDCache anymore. Adding ECC to the self-contained caches would be an interesting project.
