### ISSUE TITLE
rv64um* tests not showing up in generated-src/*.d makefrag.

### ISSUE THREAD

**Issue by ccelio** [riscv-boom/riscv-boom#67]
The makefile test targets are auto-generated by https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/system/Generator.scala#L107. 

The error may be somewhere in here:
https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/system/Generator.scala#L13-L21

**Comment by codelec** [comment]
```bash
rv64um-v-asm-tests = \
	rv64um-v-mul \
	rv64um-v-mulh \
	rv64um-v-mulhsu \
	rv64um-v-mulhu \
	rv64um-v-div \
	rv64um-v-divu \
	rv64um-v-rem \
	rv64um-v-remu \
	rv64um-v-divuw \
	rv64um-v-divw \
	rv64um-v-mulw \
	rv64um-v-remuw \
	rv64um-v-remw
```
they do appear in the *.d file
alternatively you can take a look at the logs here https://circleci.com/gh/codelec/project-template/41

**Comment by ccelio** [comment]
Thanks for the clarification.  It's missing the `rv64um-p` versions.
