### ISSUE TITLE
BOOM can run big benchmarks like TPC-H?

### ISSUE THREAD

**Issue by OneDirection9** [riscv-boom/riscv-boom#78]
Hi, all
  I want to know whether BOOM can run big benchmarks like TPC-H, database, and so on. If can, how to run it.

Thanks.

**Comment by ccelio** [comment]
BOOM supports RV64G and the Privileged ISA v1.11-draft. 

Before trying these benchmarks on BOOM, I would verify they work using spike (https://github.com/riscv/riscv-isa-sim) first. You will almost certainly need to run these benchmarks on top of Linux. Once you have figured that out and shown spike to work, you can simply replace "spike ..." with "./emulator-...-BoomConfig ...".
