### ISSUE TITLE
I  have a question  about full virtualization

### ISSUE THREAD

**Issue by changeyourname** [riscv-boom/riscv-boom#8]
I  want to know how to implement with hardware assistance (fully virtualized),Do you have a good idea,where I  can find  some material

**Comment by ccelio** [comment]
There is currently no RISC-V specification for hypervisor support, so I'm afraid I can't really provide much of an opinion on how to implement hardware assistance for virtualization in BOOM.  Much of the control/status/priveleged hardware is abstracted into the CSRFile, which is actually a part of the Rocket processor (https://github.com/ucb-bar/rocket), so if you wanted to add virtualization, I'd first add it to Rocket before adding it to BOOM.
