### ISSUE TITLE
Speculative load wakeups are very brittle.

### ISSUE THREAD

**Issue by jerryz123** [riscv-boom/riscv-boom#94]
https://github.com/ucb-bar/riscv-boom/blob/aaf42c950cd1620d7b6c4e6cc22b43aa306f3739/src/main/scala/exu/core.scala#L646-L655

In my vector-pipeline work, enabling the vector pipeline adds a queue between the MemExeUnit and the LSU. This lets me queue up vector addresses, and lets the LSU spin through them very quickly. However this also breaks the speculative load wakeup system, which assumes a fixed latency between issuing memory ops and receiving the Nacks for them.

The fix I see for this is to change iss_loadIssued to lsu_loadIssued, and have this signal trigger when the LSU reads an exe_resp. This will also decrease the length of that Pipe (to 2 I think?).

Will this have significant performance repercussions for integer-only code? It seems fine to me, but I may be overlooking something.

**Comment by ccelio** [comment]
Hmmmm, I can't think of any reason your proposal wouldn't work off the top of my head.
